# Generated by Django 3.2.16 on 2022-10-29 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('types', models.CharField(max_length=100)),
                ('characteristics', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'components',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='UserComponentPivot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.component')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.user')),
            ],
            options={
                'db_table': 'components_users_pivot',
            },
        ),
    ]
